### ISSUE TITLE
BroadcastReceiver components are not allowed to register to receive intents

### ISSUE THREAD

**Issue by bmc08gt** [BMc08GT/WerarResponses-issue-tracker#1]
User crash submitted as Bug report from LG G3 on 5.0

```
android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:212)
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:201)
at com.google.android.gms.common.api.c$2.onConnectionSuspended(Unknown Source)
at com.google.android.gms.internal.jm.aE(Unknown Source)
at com.google.android.gms.internal.jl$a.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by bmc08gt** [comment]
Looks like using the passed context to get the ApplicationContext() should resolve this issue.

EDIT: Looks like this has been the method to register the receiver since 1.2 at least. Will need further research.

**Comment by rahul-kumawat-vts** [comment]
> Looks like using the passed context to get the ApplicationContext() should resolve this issue.
> 
> EDIT: Looks like this has been the method to register the receiver since 1.2 at least. Will need further research.


Is it working after you have replaced the context with ApplicationContext() ?

**Comment by drguthrie** [comment]
Thank You. This solved the problem for me that arose when I switched from context.registerReceiver to ContextCompat.registerReceiver. Replacing the context of the BroadcastReceiver with the ApplicationContext got it back up and running.
